### PR TITLE
CSS/HTML adjustments for handbook.getdbt.com

### PR DESCRIPTION
**Pull request by john-rock**
## Description of Changes

- Updates brand color
- Reorders sidebar
- Centers footer logo and links logo to WWW

## Preview Links

https://deploy-preview-12--handbook-getdbt-com.netlify.app/docs/about_dbt_labs

### CODE REVIEW

**Comment by lfracalossiFA** [comment]
We'll want to fix this weird blob of the old color on mobile, and how the "docs" link wraps (if we're keeping it -- I argue we should ditch it)

Screenshot 2023-04-18 at 10 22 39 AM

It's not critical, but I think the heading on mobile could use more top padding/margin:
Screenshot 2023-04-18 at 10 23 47 AM

I'm seeing this error come from xhr.js in the console. Anything to worry about?
Screenshot 2023-04-18 at 10 26 40 AM

**Comment by john-rock** [comment]
@lfracalossiFA just requested another round of review after applying the changes requested in the Asana task. Are you still seeing that console error? I'm not seeing it on my end.

**Comment by lfracalossiFA** [comment]
> Are you still seeing that console error? I'm not seeing it on my end.

I don't see it on the homepage, but I see it elsewhere. It's possible it's just something that isn't working in the dev environment due to CORS restrictions (especially since it's from a file called xhr.js). I wouldn't worry too much about it.

**Review by lfracalossiFA — APPROVED** [review]
Ope, I thought I had already approved it!

**Pull request merged**
